### ISSUE TITLE
Ramlethal's swordless hitboxes show up even with swords

### ISSUE THREAD

**Issue by WesselKuipers** [AltimorTASDK/strivehitboxes#1]
First of all thanks for making this! It's looking pretty slick already! 👍 

See screenshots below, it seems to default to reading out Ram's swordless hitboxes even when she has her swords.

![](https://cdn.discordapp.com/attachments/402165550530428948/854363589208703046/unknown.png)
![](https://cdn.discordapp.com/attachments/402165550530428948/854364545036058640/unknown.png)
![](https://cdn.discordapp.com/attachments/402165550530428948/854363634674565130/unknown.png)

**Comment by AltimorTASDK** [comment]
Fixed by v1.1
