### ISSUE TITLE
Is it possible to include the on/off option?

### ISSUE THREAD

**Issue by shun9092** [AltimorTASDK/strivehitboxes#12]
To exit this mode, I have no choice to exit the game.

Is it possible to add the mode on/off option?

And can you make the color of the hitbox lighter?

I think it's too dark when several identical colors overlap.

**Comment by AltimorTASDK** [comment]
In-game toggles and custom hitbox colors/translucency are planned.

You shouldn't have hitboxes of the same type/color overlapping on the latest version unless characters are standing next to each other, since hitboxes are now merged into one continuous shape.

**Comment by shun9092** [comment]
Is this normal?

I downloaded 1.2.1 version.

https://imgur.com/Kapl3Ed

**Comment by AltimorTASDK** [comment]
Nope, that'll be fixed as soon as the next version is released
