### ISSUE TITLE
Ramlethal j.S hitboxes aren't shown at their full length.

### ISSUE THREAD

**Issue by brandon-dodds** [AltimorTASDK/strivehitboxes#4]
![image](https://user-images.githubusercontent.com/60390818/122121647-cb9a5b00-ce23-11eb-92eb-6498ff766f27.png)

Attached is May getting hit by j.S but the hitbox for j.S is not shown on the sword.

**Comment by AltimorTASDK** [comment]
Fixed by v1.1
