### ISSUE TITLE
Hey I was trying to find you to ask you, but could you do the same thing for dbfz?

### ISSUE THREAD

**Issue by SuprLarry** [AltimorTASDK/strivehitboxes#5]
IIrc you were the person behind the dbfz hitbox viewer, but the dbfz community really would like an update for the dbfz one if you could.  I really appreciate the work you've done and I hope you have a wonderful day.  

discord is SuprLarry#7543 and Twitter is @SuprLarry

**Comment by AltimorTASDK** [comment]
I'll most likely be focused on Strive for a while.
