### ISSUE TITLE
Axl charge S doesn't show properly.

### ISSUE THREAD

**Issue by brandon-dodds** [AltimorTASDK/strivehitboxes#6]
![image](https://user-images.githubusercontent.com/60390818/122209007-edcfbf80-ce9b-11eb-9db7-d7b39c3c1e8c.png)

**Comment by brandon-dodds** [comment]
![image](https://user-images.githubusercontent.com/60390818/122209481-79495080-ce9c-11eb-8a8d-42a5dcfa4a42.png)
Following up, here are the frames before the first hit and directly on the first hit (sorry for the awful compression)
![image](https://user-images.githubusercontent.com/60390818/122209551-8f571100-ce9c-11eb-81ba-7a83ce505a0a.png)

**Comment by AltimorTASDK** [comment]
Fixed by v1.1.1
